### ISSUE TITLE
Build issues (OCC-313)

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore.Commerce#524]
### Describe the bug

I tried starting the solution with Visual Studio and VS Code and both failed to compile.

With Visual Studio I'm getting an issue with corepack and/or pnpm

![Image](https://github.com/user-attachments/assets/be8f0f50-97aa-4dbf-94e5-0fb20ca377ce)

With VS Code the launcher is still trying to use net6.0.

After fixing the launcher I get the same error for pnpm.

![Image](https://github.com/user-attachments/assets/45286734-44f0-4017-851f-2f07f17bf381)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-313)

**Comment by sarahelsaig** [comment]
Yes, apparently the NPM people have changed something earlier this month about how signatures are handled and that broke corepack automation for anyone who uses a different package manager such as PNPM (what we use), Yarn, etc. This should only be a problem if you use OCC from Git instead of NuGet.

I think there is already a hotfix so updating the Lombiq.NodeJs.Extensions package to [2.1.2](https://www.nuget.org/packages/Lombiq.NodeJs.Extensions/2.1.2) should fix the problem in the short term (PR is coming shortly). In the long term I'd like to re-evaluate if we can shed the node.js dependency in OCC.

**Comment by Skrypt** [comment]
Yeah Corepack seems to have issues these days. I'll take a look at Commerce when it is fixed. Thanks.

**Comment by Skrypt** [comment]
I'm still having issues after merging lastest commit:

![Image](https://github.com/user-attachments/assets/786bca7e-b188-4f7a-9f70-2cf4d065ebb9)

**Comment by sarahelsaig** [comment]
It says "operation not permitted" which suggests an unrelated permission error on your local machine. A quick search around [suggests](https://stackoverflow.com/questions/70577085/nodejs-will-not-enable-corepack-operation-not-permitted) that running `corepack enable` as an admin may fix the problem. If not, then this is an upstream problem with Lombiq.NodeJs.Extensions on Windows.

**Comment by Skrypt** [comment]
I tried running it in Visual Studio which runs in administrative mode all the time and had the same issue.

**Comment by Skrypt** [comment]
So, I needed to compile in Visual Studio. And it warned me of an access to my user document folder. Which got refused but still started the website with IISExpress. Then I need to run Visual Studio Code as an administrator to make it compile the javascript assets. Else, the command is not executed because of permissions.
